server:
  port: 9099

app:
  map:
    path: "C:/projects/carte.txt"
  instructions:
    dir: "C:/projects"


  spring:
    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB
